--Drop all the tables in the database
DROP TABLE IF EXISTS Customer CASCADE;

DROP TABLE IF EXISTS Employee CASCADE;

DROP TABLE IF EXISTS Product CASCADE;

DROP TABLE IF EXISTS Insurance CASCADE;

DROP TABLE IF EXISTS Supplier CASCADE;

DROP TABLE IF EXISTS Orders CASCADE;

DROP TABLE IF EXISTS Discounts CASCADE;

DROP TABLE IF EXISTS Prescription CASCADE;

DROP TABLE IF EXISTS Contains CASCADE;

DROP TABLE IF EXISTS Restocks CASCADE;

DROP TABLE IF EXISTS OrdersFrom CASCADE;

DROP TABLE IF EXISTS Covers CASCADE;

DROP TABLE IF EXISTS Ships CASCADE;

DROP TABLE IF EXISTS Provides CASCADE;
