INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 121, 'PERFECTION LUMIERE', 'Uriel Pharmacy Inc', 191, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 31, 'Methocarbamol', 'Pfizer Consumer Healthcare', 165, 'TRUE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 15, 'Lidocaine Hydrochloride', 'Antigen Laboratories Inc', 159, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 131, 'Listerine', 'Infirst Healthcare', 17, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 101, 'Clarithromycin', 'Cardinal Health', 163, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 42, 'SERTRALINE', 'Clinical Solutions Wholesale', 226, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 16, 'Ibuprofen', 'Antigen Laboratories Inc', 104, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 38, 'MORPHINE SULFATE', 'Infirst Healthcare', 131, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 149, 'Citalopram', 'Antigen Laboratories Inc', 201, 'TRUE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 103, 'allergy relief', 'Cardinal Health', 244, 'TRUE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 39, 'HEADACHE', 'Infirst Healthcare', 73, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 21, 'Potassium Chloride in Dextrose and Sodium Chloride', 'Proficient Rx LP', 34, 'TRUE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 110, 'Berkley and Jensen Nasal Decongestant PE', 'Medline Industries', 149, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 110, 'Childrens Day Time Cold and Cough', 'Proficient Rx LP', 167, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 115, 'Imipramine Hydrochloride', 'Antigen Laboratories Inc', 198, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 55, 'Enoxaparin Sodium', 'Pfizer Consumer Healthcare', 160, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 43, 'Sinus and Cold D', 'Medline Industries', 89, 'TRUE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 103, 'QUALITY CHOICE Antibacterial Moist Towelettes', 'Pfizer Consumer Healthcare', 241, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 149, 'ATORVASTATIN CALCIUM', 'Cardinal Health', 193, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 92, 'Plexion', 'Proficient Rx LP', 43, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 146, 'waterless anti bacterial hand sanitizer', 'Infirst Healthcare', 14, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 10, 'Neutrogena Oil Free Acne Wash', 'Cardinal Health', 191, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 150, 'Aero CleansE2 Antibacterial', 'Cardinal Health', 193, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 115, 'Diclofenac Sodium', 'Infirst Healthcare', 117, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 66, 'Caverject', 'Uriel Pharmacy Inc', 127, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 45, 'Aquavit Etheric Energizer', 'Cardinal Health', 136, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 19, 'Powerful Pain Medicine', 'Cardinal Health', 162, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 105, 'Imipramine Hydrochloride', 'Clinical Solutions Wholesale', 224, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 36, 'Kiwi', 'Cardinal Health', 197, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 105, 'EZ PAIN RELIEVING', 'Proficient Rx LP', 168, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 138, 'Fluocinonide', 'Top Care', 118, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 143, 'Freshorize', 'Medline Industries', 137, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 97, 'BareMinerals', 'Antigen Laboratories Inc', 168, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 150, 'LIPSTICK QUEEN ENDLESS SUMMER Broad Spectrum SPF 15 Sunscreen', 'Cardinal Health', 41, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 47, 'Oxygen', 'Antigen Laboratories Inc', 47, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 102, 'daytime', 'Proficient Rx LP', 208, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 118, 'Metronidazole', 'Infirst Healthcare', 27, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 91, 'Raggedy Ann and Andy Foam', 'Medline Industries', 82, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 144, 'Modesa anti-bacterial hand gel', 'Cardinal Health', 15, 'TRUE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 67, 'Phenazopyridine HCl', 'Antigen Laboratories Inc', 114, 'TRUE');
