INSERT INTO Supplier (s_id, s_name) VALUES (DEFAULT, 'Pfizer Consumer Healthcare');
INSERT INTO Supplier (s_id, s_name) VALUES (DEFAULT, 'Cardinal Health');
INSERT INTO Supplier (s_id, s_name) VALUES (DEFAULT, 'Medline Industries');
INSERT INTO Supplier (s_id, s_name) VALUES (DEFAULT, 'Top Care');
INSERT INTO Supplier (s_id, s_name) VALUES (DEFAULT, 'Infirst Healthcare');
INSERT INTO Supplier (s_id, s_name) VALUES (DEFAULT, 'Antigen Laboratories Inc');
INSERT INTO Supplier (s_id, s_name) VALUES (DEFAULT, 'Proficient Rx LP');
INSERT INTO Supplier (s_id, s_name) VALUES (DEFAULT, 'Uriel Pharmacy Inc');
INSERT INTO Supplier (s_id, s_name) VALUES (DEFAULT, 'BioActive Nutritional Inc');
INSERT INTO Supplier (s_id, s_name) VALUES (DEFAULT, 'Clinical Solutions Wholesale');
