INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 121, 'PERFECTION LUMIERE', 'Uriel Pharmacy Inc', 586, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 31, 'Methocarbamol', 'Pfizer Consumer Healthcare', 737, 'TRUE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 15, 'Lidocaine Hydrochloride', 'Antigen Laboratories Inc', 477, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 131, 'Listerine', 'Infirst Healthcare', 469, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 101, 'Clarithromycin', 'Cardinal Health', 585, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 42, 'SERTRALINE', 'Clinical Solutions Wholesale', 765, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 34, 'quetiapine fumarate', 'Antigen Laboratories Inc', 204, 'TRUE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 38, 'MORPHINE SULFATE', 'Infirst Healthcare', 734, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 149, 'Citalopram', 'Antigen Laboratories Inc', 914, 'TRUE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 103, 'allergy relief', 'Cardinal Health', 219, 'TRUE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 39, 'HEADACHE', 'Infirst Healthcare', 180, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 21, 'Potassium Chloride in Dextrose and Sodium Chloride', 'Proficient Rx LP', 512, 'TRUE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 110, 'Berkley and Jensen Nasal Decongestant PE', 'Medline Industries', 206, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 110, 'Childrens Day Time Cold and Cough', 'Proficient Rx LP', 914, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 115, 'Imipramine Hydrochloride', 'Antigen Laboratories Inc', 947, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 55, 'Enoxaparin Sodium', 'Pfizer Consumer Healthcare', 435, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 43, 'Sinus and Cold D', 'Medline Industries', 540, 'TRUE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 103, 'QUALITY CHOICE Antibacterial Moist Towelettes', 'Pfizer Consumer Healthcare', 254, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 149, 'ATORVASTATIN CALCIUM', 'Cardinal Health', 872, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 92, 'Plexion', 'Proficient Rx LP', 775, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 146, 'waterless anti bacterial hand sanitizer', 'Infirst Healthcare', 308, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 10, 'Neutrogena Oil Free Acne Wash', 'Cardinal Health', 865, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 150, 'Aero CleansE2 Antibacterial', 'Cardinal Health', 151, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 115, 'Diclofenac Sodium', 'Infirst Healthcare', 154, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 66, 'Caverject', 'Uriel Pharmacy Inc', 554, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 45, 'Aquavit Etheric Energizer', 'Cardinal Health', 348, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 19, 'Powerful Pain Medicine', 'Cardinal Health', 226, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 105, 'Imipramine Hydrochloride', 'Clinical Solutions Wholesale', 195, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 36, 'Kiwi', 'Cardinal Health', 530, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 105, 'EZ PAIN RELIEVING', 'Proficient Rx LP', 343, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 138, 'Fluocinonide', 'Top Care', 565, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 143, 'Freshorize', 'Medline Industries', 740, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 97, 'BareMinerals', 'Antigen Laboratories Inc', 232, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 150, 'LIPSTICK QUEEN ENDLESS SUMMER Broad Spectrum SPF 15 Sunscreen', 'Cardinal Health', 578, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 47, 'Oxygen', 'Antigen Laboratories Inc', 606, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 102, 'daytime', 'Proficient Rx LP', 231, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 118, 'Metronidazole', 'Infirst Healthcare', 923, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 91, 'Raggedy Ann and Andy Foam', 'Medline Industries', 958, 'FALSE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 144, 'Modesa anti-bacterial hand gel', 'Cardinal Health', 759, 'TRUE');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (DEFAULT, 67, 'Phenazopyridine HCl', 'Antigen Laboratories Inc', 522, 'TRUE');
