INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (1, 121, 'PERFECTION LUMIERE', 'Uriel Pharmacy Inc', 586, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (2, 31, 'Methocarbamol', 'Pfizer Consumer Healthcare', 737, 'true');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (3, 15, 'Lidocaine Hydrochloride', 'Antigen Laboratories Inc', 477, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (4, 131, 'Listerine', 'Infirst Healthcare', 469, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (5, 101, 'Clarithromycin', 'Cardinal Health', 585, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (6, 42, 'SERTRALINE', 'Clinical Solutions Wholesale', 765, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (7, 34, 'quetiapine fumarate', 'Antigen Laboratories Inc', 204, 'true');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (8, 38, 'MORPHINE SULFATE', 'Infirst Healthcare', 734, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (9, 149, 'Citalopram', 'Antigen Laboratories Inc', 914, 'true');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (10, 103, 'allergy relief', 'Cardinal Health', 219, 'true');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (11, 39, 'HEADACHE', 'Infirst Healthcare', 180, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (12, 21, 'Potassium Chloride in Dextrose and Sodium Chloride', 'Proficient Rx LP', 512, 'true');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (13, 110, 'Berkley and Jensen Nasal Decongestant PE', 'Medline Industries', 206, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (14, 110, 'Childrens Day Time Cold and Cough', 'Proficient Rx LP', 914, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (15, 115, 'Imipramine Hydrochloride', 'Antigen Laboratories Inc', 947, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (16, 55, 'Enoxaparin Sodium', 'Pfizer Consumer Healthcare', 435, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (17, 43, 'Sinus and Cold D', 'Medline Industries', 540, 'true');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (18, 103, 'QUALITY CHOICE Antibacterial Moist Towelettes', 'Pfizer Consumer Healthcare', 254, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (19, 149, 'ATORVASTATIN CALCIUM', 'Cardinal Health', 872, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (20, 92, 'Plexion', 'Proficient Rx LP', 775, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (21, 146, 'waterless anti bacterial hand sanitizer', 'Infirst Healthcare', 308, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (22, 10, 'Neutrogena Oil Free Acne Wash', 'Cardinal Health', 865, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (23, 150, 'Aero CleansE2 Antibacterial', 'Cardinal Health', 151, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (24, 115, 'Diclofenac Sodium', 'Infirst Healthcare', 154, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (25, 66, 'Caverject', 'Uriel Pharmacy Inc', 554, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (26, 45, 'Aquavit Etheric Energizer', 'Cardinal Health', 348, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (27, 19, 'Powerful Pain Medicine', 'Cardinal Health', 226, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (28, 105, 'Imipramine Hydrochloride', 'Clinical Solutions Wholesale', 195, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (29, 36, 'Kiwi', 'Cardinal Health', 530, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (30, 105, 'EZ PAIN RELIEVING', 'Proficient Rx LP', 343, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (31, 138, 'Fluocinonide', 'Top Care', 565, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (32, 143, 'Freshorize', 'Medline Industries', 740, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (33, 97, 'BareMinerals', 'Antigen Laboratories Inc', 232, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (34, 150, 'LIPSTICK QUEEN ENDLESS SUMMER Broad Spectrum SPF 15 Sunscreen', 'Cardinal Health', 578, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (35, 47, 'Oxygen', 'Antigen Laboratories Inc', 606, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (36, 102, 'daytime', 'Proficient Rx LP', 231, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (37, 118, 'Metronidazole', 'Infirst Healthcare', 923, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (38, 91, 'Raggedy Ann and Andy Foam', 'Medline Industries', 958, 'false');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (39, 144, 'Modesa anti-bacterial hand gel', 'Cardinal Health', 759, 'true');
INSERT INTO Product (p_id, p_price, p_name, p_supplier, p_quantity, p_PrescriptionNeeded) VALUES (40, 67, 'Phenazopyridine HCl', 'Antigen Laboratories Inc', 522, 'true');
