INSERT INTO Supplier (s_id, s_name) VALUES (1, 'Pfizer Consumer Healthcare');
INSERT INTO Supplier (s_id, s_name) VALUES (2, 'Cardinal Health');
INSERT INTO Supplier (s_id, s_name) VALUES (3, 'Medline Industries');
INSERT INTO Supplier (s_id, s_name) VALUES (4, 'Top Care');
INSERT INTO Supplier (s_id, s_name) VALUES (5, 'Infirst Healthcare');
INSERT INTO Supplier (s_id, s_name) VALUES (6, 'Antigen Laboratories Inc');
INSERT INTO Supplier (s_id, s_name) VALUES (7, 'Proficient Rx LP');
INSERT INTO Supplier (s_id, s_name) VALUES (8, 'Uriel Pharmacy Inc');
INSERT INTO Supplier (s_id, s_name) VALUES (9, 'BioActive Nutritional Inc');
INSERT INTO Supplier (s_id, s_name) VALUES (10, 'Clinical Solutions Wholesale');
